---
BASE: "{{ lookup('env', 'BASE')|default('/opt/stack', true) }}"
CI_USER: "{{ lookup('env', 'CI_USER')|default(ansible_user_id, true) }}"
PING_TIMES: 20
HTTP_TIMES: 10
PIP_CONFIG_FILE: "{{ lookup('env', 'PIP_CONFIG_FILE')|default('/etc/pip.conf', true) }}"
